Update advanced-configuration.md
Atlas-OS/docs pull request #78
Opened 2023-05-07 10:20 UTC by Wonderingg

### Type
- [ ] Rewrite already written documentation.
- [ ] Add/remove new pages.

### Questions
- [ ] Did you preview on your local machine beforehand?
- [ ] Did you follow our [commit handbook](https://github.com/Atlas-OS/docs/blob/master/.github/CONTRIBUTING.md#commit-message)?

### Describe your pull request
fix: 🐛 Boot Configuration
fix: 🐛 NVIDIA Display Container

2023-05-07 10:34 UTC, JayXTQ requested changes
If you wish for this to be pushed, please provide more information.

2023-05-07 11:42 UTC, Wonderingg commented
> If you wish for this to be pushed, please provide more information.

More information about the files i changed or more information in the docs that i changed?

2023-05-07 11:48 UTC, JayXTQ commented
More information about the topics you wrote for. Check the configuration based pages for more examples of this

2023-05-09 16:13 UTC, Xyueta approved these changes

2023-05-13 15:26 UTC, JayXTQ approved these changes

2023-05-13 15:27 UTC, merged